### ISSUE TITLE
Minimum Viable Product

### ISSUE THREAD

**Issue by SamMousa** [lantisnt/ClassicLootManager#2]
Some UIs that need to be in a first version:

- [x] 1. Award UI (ML) #5 
- [x] 2. Bidding UI (raider) #4 
- [x] 3. Standings UI (raider) #3
